[package]
name = "node-storage"
version = "0.4.0"
authors = ["Andrei Marinica <andrei.marinica@dharitri.com>"]
edition = "2018"

[dependencies.dharitri-sc]
version = "0.13.3"

[dev-dependencies.dharitri-sc-scenario]
version = "0.13.3"
