[package]
name = "auction-mock-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@dharitri.com>"]
edition = "2018"
publish = false

[dependencies.auction-mock]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.13.3"
default-features = false
